// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: main.sql

package models

import (
	"context"
)

const getAllAddresses = `-- name: GetAllAddresses :many
SELECT id, city, state, country, pincode, "roomNumber", "BuildingNumber", "createdAt", "updatedAt", "userId" FROM "Address"
`

func (q *Queries) GetAllAddresses(ctx context.Context) ([]Address, error) {
	rows, err := q.db.QueryContext(ctx, getAllAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Address
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.City,
			&i.State,
			&i.Country,
			&i.Pincode,
			&i.RoomNumber,
			&i.BuildingNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserId,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
