// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package models

import (
	"database/sql"
	"time"
)

type Address struct {
	ID             int32     `json:"id"`
	City           string    `json:"city"`
	State          string    `json:"state"`
	Country        string    `json:"country"`
	PinCode        string    `json:"pinCode"`
	RoomNumber     string    `json:"roomNumber"`
	BuildingNumber string    `json:"buildingNumber"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
	UserId         int32     `json:"userId"`
	IsDeleted      bool      `json:"isDeleted"`
}

type Appointment struct {
	ID             int32     `json:"id"`
	UserOneId      int32     `json:"userOneId"`
	UserTwoId      int32     `json:"userTwoId"`
	Status         int32     `json:"status"`
	Time           time.Time `json:"time"`
	Remarks        string    `json:"remarks"`
	ReferredBy     int32     `json:"referredBy"`
	PrescriptionId int32     `json:"prescriptionId"`
	Pending        bool      `json:"pending"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
	IsDeleted      bool      `json:"isDeleted"`
}

type Availability struct {
	ID        int32     `json:"id"`
	Day       string    `json:"day"`
	StartTime time.Time `json:"startTime"`
	EndTime   time.Time `json:"endTime"`
	ProfileId int32     `json:"profileId"`
	IsDeleted bool      `json:"isDeleted"`
}

type Consumable struct {
	ID              int32     `json:"id"`
	Name            string    `json:"name"`
	Type            int32     `json:"type"`
	QuantityLeft    int32     `json:"quantityLeft"`
	QuantityPerUnit int32     `json:"quantityPerUnit"`
	BatchNumber     string    `json:"batchNumber"`
	Manufacturer    string    `json:"manufacturer"`
	ExpiryDate      time.Time `json:"expiryDate"`
	CreatedAt       time.Time `json:"createdAt"`
	UpdatedAt       time.Time `json:"updatedAt"`
	IsDeleted       bool      `json:"isDeleted"`
}

type ConsumablesToPrescribedMedicine struct {
	A int32 `json:"A"`
	B int32 `json:"B"`
}

type Leave struct {
	ID        int32     `json:"id"`
	StartDate time.Time `json:"startDate"`
	EndDate   time.Time `json:"endDate"`
	Reason    string    `json:"reason"`
	ProfileId int32     `json:"profileId"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	IsDeleted bool      `json:"isDeleted"`
}

type NonConsumable struct {
	ID                int32     `json:"id"`
	Name              string    `json:"name"`
	AvailableQuantity int32     `json:"availableQuantity"`
	Type              int32     `json:"type"`
	ServicingTime     int32     `json:"servicingTime"`
	ServicingTimeUnit int32     `json:"servicingTimeUnit"`
	CreatedAt         time.Time `json:"createdAt"`
	UpdatedAt         time.Time `json:"updatedAt"`
	IsDeleted         bool      `json:"isDeleted"`
}

type Permission struct {
	ID          int32     `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	RoleIds     []int32   `json:"roleIds"`
	ResourceId  int32     `json:"resourceId"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
	IsDeleted   bool      `json:"isDeleted"`
}

type PrescribedMedicine struct {
	ID             int32     `json:"id"`
	Dosage         int32     `json:"dosage"`
	PrescriptionId int32     `json:"prescriptionId"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

type Prescription struct {
	ID        int32     `json:"id"`
	Remarks   string    `json:"remarks"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Profile struct {
	ID            int32     `json:"id"`
	Bio           string    `json:"bio"`
	RoomNumber    int32     `json:"roomNumber"`
	Sex           int32     `json:"sex"`
	Age           int32     `json:"age"`
	ContactNumber string    `json:"contactNumber"`
	MaritalStatus int32     `json:"maritalStatus"`
	BloodGroup    int32     `json:"bloodGroup"`
	Origin        string    `json:"origin"`
	LastVisit     time.Time `json:"lastVisit"`
	Designation   string    `json:"designation"`
	Department    string    `json:"department"`
	UserId        int32     `json:"userId"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
	IsDeleted     bool      `json:"isDeleted"`
}

type Resource struct {
	ID             int32     `json:"id"`
	Name           string    `json:"name"`
	Description    string    `json:"description"`
	TotalLevelsSum int32     `json:"totalLevelsSum"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
	IsDeleted      bool      `json:"isDeleted"`
}

type Role struct {
	ID          int32     `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	UserIds     []int32   `json:"userIds"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
	IsDeleted   bool      `json:"isDeleted"`
}

type RoleToUser struct {
	A int32 `json:"A"`
	B int32 `json:"B"`
}

type User struct {
	ID        int32          `json:"id"`
	UserId    sql.NullString `json:"userId"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	Name      string         `json:"name"`
	RoleIds   []int32        `json:"roleIds"`
	ProfileId sql.NullInt32  `json:"profileId"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
	IsDeleted bool           `json:"isDeleted"`
}
